Repository sanhee/baseball, pull requests merged in 2021-05, with the labels that each got.

#4 [#2] chore: home 화면 기본적인 파일 구성과 UI 설계
  fe/public/data.json
  fe/src/App.js
  fe/src/components/GameHome/GameItem.jsx
  fe/src/components/GameHome/GameLists.jsx
  fe/src/components/GameHome/GameSelect.jsx
  fe/src/components/GameHome/GameTitle.jsx
  fe/src/index.css
  fe/src/pages/Home.jsx
Labels: enhancement

#15 DB객체 맵핑
  be/src/main/java/com/team22/baseball/domain/Game.java
  be/src/main/java/com/team22/baseball/domain/Player.java
  be/src/main/java/com/team22/baseball/domain/PlayerHistory.java
  be/src/main/java/com/team22/baseball/domain/Team.java
  be/src/main/java/com/team22/baseball/domain/TeamScore.java
  be/src/main/java/com/team22/baseball/repository/GameRepository.java
  be/src/main/java/com/team22/baseball/service/GameService.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/main/resources/temp.sql
  be/src/test/java/com/team22/baseball/service/GameServiceTest.java
Labels: 백엔드

#24 Feature/header right
  README.md
  fe/package-lock.json
  fe/src/App.js
  fe/src/components/GameHome/GameLists.jsx
  fe/src/components/GamePlay/playHeader/Header.jsx
  fe/src/components/GamePlay/playHeader/HeaderScore.jsx
  fe/src/components/GamePlay/playScreen/Main.jsx
  fe/src/components/common/Span.jsx
  fe/src/styles/theme.js
  fe/yarn.lock
Labels: 프론트엔드

#29 [ #20 ]Feature/screen UI
  fe/public/field.svg
  fe/src/components/GamePlay/playScreen/BallCount.jsx
  fe/src/components/GamePlay/playScreen/BallCountItem.jsx
  fe/src/components/GamePlay/playScreen/Main.jsx
  fe/src/components/GamePlay/playScreen/Screen.jsx
  fe/src/reset.css
Labels: 프론트엔드

#31 Feature/history
  fe/src/components/GamePlay/playHeader/HeaderScore.jsx
  fe/src/components/GamePlay/playScreen/Board.jsx
  fe/src/components/GamePlay/playScreen/BoardItem.jsx
  fe/src/components/GamePlay/playScreen/History.jsx
  fe/src/components/GamePlay/playScreen/Main.jsx
  fe/src/pages/Game.jsx
Labels: enhancement, 프론트엔드

#32 API 구현
  be/src/main/java/com/team22/baseball/controller/ApiGameController.java
  be/src/main/java/com/team22/baseball/domain/TeamScore.java
  be/src/main/java/com/team22/baseball/dto/request/UpdatePlayerInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/DetailScore/detailScoreDto.java
  be/src/main/java/com/team22/baseball/dto/response/GameList/GameDto.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/PlayerDto.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/PlayerScoreDto.java
  be/src/main/java/com/team22/baseball/dto/response/PlayerScoreList/TeamDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/PlayerInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamInfoDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamListDto.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/TeamTypeDto.java
  be/src/main/java/com/team22/baseball/repository/GameRepository.java
  be/src/main/java/com/team22/baseball/service/GameService.java
Labels: 백엔드

#37 feat: ballcount
  fe/src/components/GameHome/GameContainer.jsx
  fe/src/components/GameHome/GameItem.jsx
  fe/src/components/GamePlay/playHeader/HeaderScore.jsx
  fe/src/components/GamePlay/playHeader/Pitcher.jsx
  fe/src/components/GamePlay/playScreen/Screen.jsx
  fe/src/pages/Game.jsx
Labels: 프론트엔드

#40 타자 정보 업데이트 요청 후 리스폰스 구현
  be/src/main/java/com/team22/baseball/controller/ApiGameController.java
  be/src/main/java/com/team22/baseball/dto/response/TeamSelect/NextPlayerInfoDto.java
  be/src/main/java/com/team22/baseball/repository/GameRepository.java
  be/src/main/java/com/team22/baseball/service/GameService.java
  be/src/main/resources/application.properties
  be/src/main/resources/data.sql
Labels: 백엔드

#41 Feature/ball count
  fe/src/components/GameHome/GameContainer.jsx
  fe/src/components/GamePlay/GamePlay.jsx
  fe/src/components/GamePlay/playHeader/HeaderScore.jsx
  fe/src/components/GamePlay/playHeader/Pitcher.jsx
  fe/src/components/GamePlay/playScreen/BallCount.jsx
  fe/src/components/GamePlay/playScreen/BallCountItem.jsx
  fe/src/components/GamePlay/playScreen/Screen.jsx
  fe/src/pages/Game.jsx
  fe/src/pages/Home.jsx
  fe/src/styles/FlexCenter.jsx
Labels: 프론트엔드

#38 Feature/popup
  fe/package.json
  fe/src/components/GamePlay/playPopUp/PopUp.jsx
  fe/src/components/GamePlay/playScreen/Screen.jsx
  fe/src/pages/Game.jsx
Labels: 프론트엔드
